# Generated by Django 5.2.2 on 2025-06-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
