# Generated by Django 5.2.2 on 2025-06-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasktable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
