# Generated by Django 5.2.2 on 2025-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasktable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='starting_date',
            field=models.DateField(auto_created=True),
        ),
    ]
