# Generated by Django 5.2.2 on 2025-06-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasktable_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='starting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
